"""update quiz attempt table

Revision ID: 98da9727af5b
Revises: dfe4352312e5
Create Date: 2026-08-23 22:05:01.683667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98da9727af5b'
down_revision = 'dfe4352312e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quizzes', ['quiz_id'], ['id'])

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('operation')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
