"""add quizzes and questions table

Revision ID: dfe4352312e5
Revises: c5675ab85ea6
Create Date: 2026-08-19 03:45:02.821411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe4352312e5'
down_revision = 'c5675ab85ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('choice_1', sa.String(length=50), nullable=False),
    sa.Column('choice_2', sa.String(length=50), nullable=False),
    sa.Column('choice_3', sa.String(length=50), nullable=False),
    sa.Column('choice_4', sa.String(length=50), nullable=False),
    sa.Column('correct_answer', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('questions')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
